language: java
jdk:
  - openjdk20

branches:
  only:
    - main

cache:
  directories:
    - $HOME/.m2

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS BOOKTOUR;'

script:
  - mvn clean install

notifications:
  email:
    recipients:
      - minhhieupham2002@gmail.com
    on_success: always
    on_failure: always
